import { Inter } from "next/font/google";
import "./globals.css";

//components
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import ThemeContextProvider from "@/components/ThemeContextProvider";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Project one",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ThemeContextProvider>
      <html lang="en">
        <body className={inter.className}>
          <Header />
          <PageTransition>{children}</PageTransition>
        </body>
      </html>
    </ThemeContextProvider>
  );
}
